#!/usr/bin/python

import flimflam, sys

if (len(sys.argv) < 3):
    print "Usage: %s <service-name> <property>" % (sys.argv[0])
    sys.exit(1)

(_, name, service_property) = sys.argv

flim = flimflam.FlimFlam()
service = flim.FindElementByNameSubstring('Service', name)
service.ClearProperty(service_property)
