#!/usr/bin/python
#
# Copyright (C) 2015 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

import dbus, flimflam, sys

if (len(sys.argv) < 3):
    print "Usage: %s <profile_name> <entry_name>" % (sys.argv[0])
    sys.exit(1)

(_, profile_name, entry_name) = sys.argv

flim = flimflam.FlimFlam(dbus.SystemBus())

profile = flim.FindElementByNameSubstring('Profile', profile_name)
if profile is None:
    device = flim.FindElementByPropertySubstring('Profile',
                                                 'Interface',
                                                 profile_name)

print "Found profile %s" % (profile.object_path)

try:
    properties = profile.GetEntry(entry_name)
    for key in properties.keys():
        print "    %s = %s" % \
            (key, flimflam.convert_dbus_value(properties[key], 4))
except dbus.DBusException, error:
    print "Entry %s not found" % (entry_name)
