#!/usr/bin/python
#
# Copyright (C) 2015 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

import dbus, flimflam

flim = flimflam.FlimFlam(dbus.SystemBus())

for obj in flim.GetObjectList("Profile"):
    obj_properties = obj.GetProperties(utf8_strings = True)

    print "[ %s ]" % (obj.object_path)
    for key in obj_properties.keys():
        print "    %s = %s" % \
            (key, flimflam.convert_dbus_value(obj_properties[key], 4))

print
