#!/usr/bin/python

import dbus, flimflam, sys

if (len(sys.argv) < 2):
    print "Usage: %s <service-path>" % (sys.argv[0])
    sys.exit(1)

(_, path) = sys.argv

flim = flimflam.FlimFlam(dbus.SystemBus())

service = flim.FindElementByNameSubstring("Service", path)
service.Remove()
