#!/usr/bin/python

import dbus, flimflam, sys

if (len(sys.argv) < 2):
    print "Usage: %s <country>" % (sys.argv[0])
    sys.exit(1)

(_, country) = sys.argv

flim = flimflam.FlimFlam(dbus.SystemBus())
flim.SetCountry(country)
