#!/usr/bin/python

import dbus, flimflam, sys

if (len(sys.argv) < 2):
    print "Usage: %s check-portal-list" % (sys.argv[0])
    sys.exit(1)

(_, portal_list) = sys.argv

flim = flimflam.FlimFlam(dbus.SystemBus())
flim.SetCheckPortalList(portal_list)
