#!/usr/bin/python

import dbus, flimflam, sys

if (len(sys.argv) != 2):
    print "Usage: %s <technology>" % (sys.argv[0])
    sys.exit(1)

flim = flimflam.FlimFlam(dbus.SystemBus())
flim.RequestScan(sys.argv[1])
