/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_ndkaudio_AudioRecorder */

#ifndef _Included_com_android_ndkaudio_AudioRecorder
#define _Included_com_android_ndkaudio_AudioRecorder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_ndkaudio_AudioRecorder
 * Method:    Create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_android_ndkaudio_AudioRecorder_Create
  (JNIEnv *, jobject);

/*
 * Class:     com_android_ndkaudio_AudioRecorder
 * Method:    Destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_android_ndkaudio_AudioRecorder_Destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_android_ndkaudio_AudioRecorder
 * Method:    RealizeRecorder
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_android_ndkaudio_AudioRecorder_RealizeRecorder
  (JNIEnv*, jobject);

/*
 * Class:     com_android_ndkaudio_AudioRecorder
 * Method:    RealizeRoutingProxy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_android_ndkaudio_AudioRecorder_RealizeRoutingProxy
  (JNIEnv*, jobject);

/*
 * Class:     com_android_ndkaudio_AudioRecorder
 * Method:    Start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_android_ndkaudio_AudioRecorder_Start
  (JNIEnv *, jobject);

/*
 * Class:     com_android_ndkaudio_AudioRecorder
 * Method:    Stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_android_ndkaudio_AudioRecorder_Stop
  (JNIEnv *, jobject);

/*
 * Class:     com_android_ndkaudio_AudioRecorder
 * Method:    GetRoutingInterface
 * Signature: ()Landroid/media/AudioRouting;
 */
JNIEXPORT jobject JNICALL Java_com_android_ndkaudio_AudioRecorder_GetRoutingInterface
  (JNIEnv*, jobject);

/*
 * Class:     com_android_ndkaudio_AudioRecorder
 * Method:    ReleaseRoutingInterface
 * Signature: (Landroid/media/AudioRouting;)V
 */
JNIEXPORT void JNICALL Java_com_android_ndkaudio_AudioRecorder_ReleaseRoutingInterface
  (JNIEnv*, jobject, jobject);

/*
 * Class:     com_android_ndkaudio_AudioRecorder
 * Method:    GetNumBufferFrames
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_android_ndkaudio_AudioRecorder_GetNumBufferFrames
  (JNIEnv *, jobject);

/*
 * Class:     com_android_ndkaudio_AudioRecorder
 * Method:    GetBufferData
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_com_android_ndkaudio_AudioRecorder_GetBufferData
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     com_android_ndkaudio_AudioRecorder
 * Method:    GetLastSLResult
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_android_ndkaudio_AudioRecorder_GetLastSLResult
  (JNIEnv*, jobject);

/*
 * Class:     com_android_ndkaudio_AudioRecorder
 * Method:    ClearLastSLResult
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_android_ndkaudio_AudioRecorder_ClearLastSLResult
  (JNIEnv*, jobject);

#ifdef __cplusplus
}
#endif
#endif
