INCL_CONFIG = `pkg-config --cflags glib-2.0 gobject-2.0` -g
LIB_CONFIG = `pkg-config --libs glib-2.0 gobject-2.0` -lgthread-2.0 -g

all:
	gcc -c mixparams.c -o mixparams.o $(INCL_CONFIG)
	gcc -c mixdrmparams.c -o mixdrmparams.o $(INCL_CONFIG)
	gcc -c mixvideocaps.c -o mixvideocaps.o $(INCL_CONFIG)
	gcc -c mixdisplay.c -o mixdisplay.o $(INCL_CONFIG)
	gcc -c mixdisplayx11.c -o mixdisplayx11.o $(INCL_CONFIG)
	gcc -c mixvideoinitparams.c -o mixvideoinitparams.o $(INCL_CONFIG)	
	gcc -c mixvideoconfigparams.c -o mixvideoconfigparams.o $(INCL_CONFIG)
	gcc -c mixvideoconfigparams_h264.c -o mixvideoconfigparams_h264.o $(INCL_CONFIG)
	gcc -c mixvideoconfigparams_vc1.c -o mixvideoconfigparams_vc1.o $(INCL_CONFIG)
	gcc -c mixvideodecodeparams.c -o mixvideodecodeparams.o $(INCL_CONFIG)
	gcc -c mixvideorenderparams.c -o mixvideorenderparams.o $(INCL_CONFIG)
	gcc -c mixvideoframe.c -o mixvideoframe.o $(INCL_CONFIG)
	gcc -c mixvideo.c -o mixvideo.o $(INCL_CONFIG)
	gcc -c test.c -o test.o $(INCL_CONFIG)
	gcc 	test.o \
		mixvideo.o \
		mixparams.o \
		mixdrmparams.o \
		mixvideorenderparams.o \
		mixvideodecodeparams.o \
		mixvideoconfigparams.o \
		mixvideoconfigparams_vc1.o \
		mixvideoconfigparams_h264.o \
		mixvideoinitparams.o \
		mixdisplay.o \
		mixdisplayx11.o \
		mixvideocaps.o \
		mixvideoframe.o \
		-o test $(LIB_CONFIG)		
	
clean:
	rm *~
	rm *.o
	rm test
 

