// auto generated by go tool dist

package runtime

const defaultGoroot = `./prebuilts/go/linux-x86`
const theVersion = `go1.5.1`
const goexperiment = ``
const stackGuardMultiplier = 1
var buildVersion = theVersion
