#!/bin/bash

adb push $ANDROID_PRODUCT_OUT/system/framework/cts-testng.jar /data/local/tmp
adb shell "cd /data/local/tmp && dalvikvm -cp cts-testng.jar:ctslibcore/CtsLibcoreOjTestCases.apk com.android.cts.testng.SingleTestNGTestRunner org.openjdk.tests.java.util.stream.GroupByOpTest#testOps"
